Use angle bracket syntax for amount-input
qonto/ember-amount-input pull request #368
Opened 2022-07-14 15:14 UTC by mrloop

#### Description
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
 
Update tests, docs and comments to use angle bracket syntax

2022-07-14 16:56 UTC, daltino approved these changes

2022-07-15 06:46 UTC, zeppelin requested changes
There are a bunch of component invocations that are passing numbers to args. Is it intentional? If so, wouldn't it be better to mark them explicitly as string with quotes? Same goes for booleans, It'd be likely better to wrap them to curlies.

2022-07-15 06:46 UTC, zeppelin commented on tests/dummy/app/templates/docs/components/amount-input.md
> +      @value=924.67
`typeof this.args.value === 'string'`

2022-07-15 06:46 UTC, zeppelin commented on tests/dummy/app/templates/docs/components/amount-input.md
> +      @step=1
`typeof this.args.value === 'string'`

2022-07-15 06:46 UTC, zeppelin commented on tests/dummy/app/templates/docs/components/amount-input.md
> +      @numberOfDecimal=0
`typeof this.args.value === 'string'`

2022-07-15 08:03 UTC, mrloop commented
> There are a bunch of component invocations that are passing numbers to args. Is it intentional?

No an oversight 🙈 have updated

2022-07-15 11:33 UTC, merged